/**
 * ui-text.ts — Nguồn dữ liệu văn bản duy nhất cho toàn bộ UI.
 * Để chuyển ngôn ngữ, chỉ cần sửa file này.
 */
export const UI_TEXT = {
  common: {
    home: "Trang chủ",
    loading: "Đang tải...",
    error: "Đã xảy ra lỗi",
    cancel: "Huỷ",
    save: "Lưu",
    confirm: "Xác nhận",
    delete: "Xoá",
    edit: "Sửa",
    add: "Thêm",
    search: "Tìm kiếm",
    approve: "Duyệt",
    reject: "Từ chối",
    close: "Đóng",
    submit: "Gửi",
    ok: "Đồng ý",
    free: "Miễn phí",
    copyright: (year: number) =>
      `Copyright Moon Store ${year}. Bảo lưu mọi quyền`,
  },

  header: {
    brand: "Exclusive",
    searchPlaceholder: "Bạn đang tìm gì?",
    searchAriaLabel: "Tìm kiếm",
    searchActionLabel: "Tìm kiếm",
    categoryLabel: "Danh mục",
    promoMessage:
      "Flash Sale — Giảm tới 50% cho tất cả sản phẩm! Giao hàng miễn phí.",
    promoLinkLabel: "Mua ngay",
    accountSettings: "Cài đặt tài khoản",
    myOrders: "Đơn hàng của tôi",
    messages: "Tin nhắn",
    adminConsole: "Quản trị hệ thống",
    sellerHub: "Gian hàng của tôi",
    becomeSeller: "Trở thành người bán",
    logout: "Đăng xuất",
    login: "Đăng nhập",
    cartLabel: "Giỏ hàng",
  },

  nav: {
    home: "Trang chủ",
    contact: "Liên hệ",
    about: "Giới thiệu",
    signUp: "Đăng ký",
    cart: "Giỏ hàng",
  },

  footer: {
    exclusiveTitle: "Exclusive",
    subscribeLabel: "Đăng ký nhận tin",
    subscribeDesc: "Nhận ưu đãi 10% cho đơn hàng đầu tiên",
    supportTitle: "Hỗ trợ",
    address: "111 Bijoy Sarani, Dhaka, BD",
    email: "exclusive@gmail.com",
    phone: "+88015-88888-9999",
    accountTitle: "Tài khoản",
    myAccount: "Tài khoản của tôi",
    loginRegister: "Đăng nhập / Đăng ký",
    cart: "Giỏ hàng",
    wishlist: "Danh sách yêu thích",
    shop: "Cửa hàng",
    quickLinkTitle: "Liên kết nhanh",
    privacyPolicy: "Chính sách bảo mật",
    termsOfUse: "Điều khoản sử dụng",
    faq: "Câu hỏi thường gặp",
    contact: "Liên hệ",
  },

  home: {
    banners: [
      {
        title: "Ưu đãi lên đến 10%",
        subtitle: "iPhone 14 Series",
        ctaLabel: "Mua ngay",
      },
      {
        title: "Tuần lễ Gaming",
        subtitle: "Phụ kiện RGB và màn hình sale",
        ctaLabel: "Khám phá",
      },
      {
        title: "Nâng cấp setup của bạn",
        subtitle: "Laptop, máy ảnh và thiết bị âm thanh",
        ctaLabel: "Xem ưu đãi",
      },
    ],
    sideMenu: [
      { label: "Điện thoại", children: ["Flagship", "Tầm trung", "Gập"] },
      { label: "Máy tính", children: ["Ultrabook", "Gaming", "Workstation"] },
      { label: "Đồng hồ thông minh", children: ["Thể thao", "Cao cấp"] },
      { label: "Máy ảnh", children: ["DSLR", "Mirrorless"] },
      { label: "Tai nghe", children: ["Earbuds", "Over-Ear"] },
      { label: "Gaming", children: ["Tay cầm", "Bàn phím"] },
      { label: "Thời trang", children: ["Hoodie", "Áo khoác"] },
      { label: "Nội thất", children: ["Bàn làm việc", "Ghế"] },
    ],
    services: [
      {
        title: "GIAO HÀNG MIỄN PHÍ & NHANH CHÓNG",
        description: "Miễn phí giao hàng cho đơn từ 2.000.000đ",
      },
      {
        title: "HỖ TRỢ KHÁCH HÀNG 24/7",
        description: "Hỗ trợ nhiệt tình 24/7",
      },
      {
        title: "ĐẢM BẢO HOÀN TIỀN",
        description: "Hoàn tiền trong vòng 30 ngày",
      },
    ],
    arrivals: [
      {
        title: "PlayStation 5",
        description: "Phiên bản đen trắng PS5 đang được mở bán.",
      },
      {
        title: "Bộ sưu tập nữ",
        description: "Bộ sưu tập thời trang nữ đặc sắc.",
      },
      { title: "Loa", description: "Loa không dây Amazon" },
      { title: "Nước hoa", description: "GUCCI INTENSE OUD EDP" },
    ],
  },

  auth: {
    login: {
      title: "Đăng nhập vào Exclusive",
      subtitle: "Nhập thông tin của bạn bên dưới",
      emailPlaceholder: "Email hoặc số điện thoại",
      passwordPlaceholder: "Mật khẩu",
      loadingLabel: "Đang đăng nhập...",
      submitLabel: "Đăng nhập",
      forgotPassword: "Quên mật khẩu?",
      signupHint: "Chưa có tài khoản?",
      signupLabel: "Đăng ký",
    },
    register: {
      title: "Tạo tài khoản",
      subtitle: "Nhập thông tin của bạn bên dưới",
      namePlaceholder: "Họ và tên",
      emailPlaceholder: "Email hoặc số điện thoại",
      passwordPlaceholder: "Mật khẩu",
      loadingLabel: "Đang tạo tài khoản...",
      submitLabel: "Tạo tài khoản",
      googleLabel: "Đăng ký với Google",
      loginHint: "Đã có tài khoản?",
      loginLabel: "Đăng nhập",
    },
  },

  account: {
    breadcrumbPrefix: "Trang chủ /",
    breadcrumbCurrent: "Tài khoản của tôi",
    welcomePrefix: "Xin chào!",
    profileTitle: "Chỉnh sửa hồ sơ",
    passwordTitle: "Đổi mật khẩu",
    currentPasswordPlaceholder: "Mật khẩu hiện tại",
    newPasswordPlaceholder: "Mật khẩu mới",
    confirmPasswordPlaceholder: "Xác nhận mật khẩu mới",
    cancelLabel: "Huỷ",
    saveLabel: "Lưu thay đổi",
    manageTitle: "Quản lý tài khoản",
    orderTitle: "Đơn hàng của tôi",
    wishlistTitle: "Danh sách yêu thích",
    myOrders: "Xem đơn hàng",
    manageItems: [
      { key: "profile" as const, label: "Hồ sơ của tôi" },
      { key: "address" as const, label: "Sổ địa chỉ" },
      { key: "payment" as const, label: "Phương thức thanh toán", disabled: true },
    ],
    firstNameLabel: "Tên",
    lastNameLabel: "Họ",
    emailLabel: "Email",
    addressLabel: "Địa chỉ",
    sellerHubTitle: "Gian hàng",
    sellerActiveDesc: "Quản lý danh mục sản phẩm và đăng bán hàng mới.",
    sellerInactiveDesc:
      "Nộp đơn đăng ký để trở thành người bán. Admin sẽ xét duyệt.",
    openSellerHub: "Vào gian hàng",
    becomeSeller: "Trở thành người bán",
    myAddresses: "Địa chỉ của tôi",
    addAddress: "Thêm địa chỉ",
    noAddresses: "Chưa có địa chỉ nào",
    isDefault: "Mặc định",
    setDefault: "Đặt mặc định",
    editAddress: "Sửa",
    removeAddress: "Xoá",
    removeAddressConfirm: "Xoá địa chỉ này?",
    removeAddressOk: "Xoá",
    addAddressTitle: "Thêm địa chỉ",
    editAddressTitle: "Sửa địa chỉ",
    saveAddressOk: "Lưu",
    addressLineLabel: "Địa chỉ",
    addressLineRequired: "Vui lòng nhập địa chỉ",
    addressLinePlaceholder: "123 Lê Lợi",
    districtLabel: "Quận / Huyện",
    districtRequired: "Vui lòng nhập quận / huyện",
    districtPlaceholder: "Quận 1",
    cityLabel: "Thành phố",
    cityRequired: "Vui lòng nhập thành phố",
    cityPlaceholder: "Hồ Chí Minh",
    setAsDefault: "Đặt làm mặc định",
  },

  cart: {
    breadcrumbLabel: "Giỏ hàng",
    pageTitle: "Giỏ hàng của tôi",
    headerProduct: "Sản phẩm",
    headerPrice: "Đơn giá",
    headerQuantity: "Số lượng",
    headerSubtotal: "Thành tiền",
    headerAction: "Thao tác",
    selectAll: "Chọn tất cả",
    deleteSelected: "Xoá",
    totalLabel: "Tổng cộng",
    selectedCount: (count: number) => `Đã chọn (${count})`,
    checkoutLabel: "Mua hàng",
    returnToShop: "Tiếp tục mua sắm",
    emptyTitle: "Giỏ hàng của bạn đang trống",
    emptyHint: "Hãy duyệt sản phẩm và thêm vào giỏ hàng.",
    emptyAction: "Khám phá ngay",
    removeConfirmTitle: "Xoá sản phẩm này khỏi giỏ?",
    removeConfirmOk: "Xoá",
    removeConfirmCancel: "Giữ lại",
    removeSelectedConfirmTitle: (count: number) =>
      `Xoá ${count} sản phẩm khỏi giỏ?`,
    selectItemsHint: "Vui lòng chọn sản phẩm để mua.",
    removeAriaLabel: (name: string) => `Xoá ${name}`,
    quantityAriaLabel: (name: string) => `Số lượng ${name}`,
    decreaseQty: "Giảm số lượng",
    increaseQty: "Tăng số lượng",
  },

  checkout: {
    breadcrumbItems: ["Tài khoản", "Giỏ hàng của tôi", "Sản phẩm", "Xem giỏ hàng", "Thanh toán"],
    billingTitle: "Thông tin thanh toán",
    savedAddressLabel: "Địa chỉ đã lưu",
    newAddressOption: "+ Dùng địa chỉ mới",
    isDefault: "(mặc định)",
    saveInfoLabel: "Lưu thông tin này cho lần thanh toán tiếp theo",
    firstName: "Họ và tên *",
    companyName: "Tên công ty",
    streetAddress: "Địa chỉ *",
    apartment: "Căn hộ, tầng, v.v. (tùy chọn)",
    city: "Thành phố / Quận *",
    phone: "Số điện thoại *",
    email: "Địa chỉ email *",
    couponPlaceholder: "Mã giảm giá",
    applyCouponLabel: "Áp dụng",
    placeOrderLabel: "Đặt hàng",
    subtotal: "Tạm tính:",
    shipping: "Phí vận chuyển:",
    discount: "Giảm giá:",
    total: "Tổng cộng:",
    freeShipping: "Miễn phí",
    noDiscount: "-",
    paymentQR: "Chuyển khoản QR",
  },

  contact: {
    breadcrumb: "Trang chủ / Liên hệ",
    namePlaceholder: "Họ và tên *",
    emailPlaceholder: "Email *",
    phonePlaceholder: "Số điện thoại *",
    messagePlaceholder: "Nội dung tin nhắn",
    submitLabel: "Gửi tin nhắn",
    requiredMessage: "Vui lòng điền đầy đủ các trường bắt buộc.",
    successMessage: "Gửi tin nhắn thành công.",
    callTitle: "Liên hệ qua điện thoại",
    callDesc: "Hỗ trợ 24/7, 7 ngày một tuần.",
    callPhone: "Điện thoại: +8801611112222",
    writeTitle: "Liên hệ qua email",
    writeDesc: "Điền vào form và chúng tôi sẽ liên hệ trong vòng 24 giờ.",
    writeEmail1: "Email: customer@exclusive.com",
    writeEmail2: "Email: support@exclusive.com",
  },

  about: {
    story: {
      title: "Câu chuyện của chúng tôi",
      para1: "Ra mắt năm 2015, Exclusive là sàn thương mại điện tử hàng đầu Nam Á với sự hiện diện tích cực tại Việt Nam.",
      para2: "Exclusive có hơn 1 triệu sản phẩm, tăng trưởng nhanh với nhiều danh mục đa dạng.",
    },
    breadcrumbAbout: "Giới thiệu",
    stats: [
      { title: "10.5k", text: "Người bán đang hoạt động" },
      { title: "33k", text: "Sản phẩm bán mỗi tháng", featured: true },
      { title: "45.5k", text: "Khách hàng hoạt động" },
      { title: "25k", text: "Doanh thu gộp hàng năm" },
    ],
    team: [
      { name: "Tom Cruise", role: "Người sáng lập & Chủ tịch" },
      { name: "Emma Watson", role: "Giám đốc điều hành" },
      { name: "Will Smith", role: "Nhà thiết kế sản phẩm" },
    ],
    services: [
      { title: "GIAO HÀNG NHANH & MIỄN PHÍ", desc: "Miễn phí giao hàng cho đơn từ 2.000.000đ" },
      { title: "HỖ TRỢ KHÁCH HÀNG 24/7", desc: "Đội ngũ hỗ trợ thân thiện 24/7" },
      { title: "ĐẢM BẢO HOÀN TIỀN", desc: "Hoàn tiền trong vòng 30 ngày" },
    ],
  },

  product: {
    notFound: "Không tìm thấy sản phẩm",
    notFoundDesc: "Sản phẩm này không tồn tại hoặc đã bị ẩn.",
    backToHome: "Về trang chủ",
    loading: "Đang tải sản phẩm...",
    store: "Cửa hàng",
    reviewsCount: (count: number) => `${count} đánh giá`,
    inStock: "Còn hàng",
    outOfStock: "Hết hàng",
    oldPriceLabel: "Giá cũ",
    installment: (monthly: string) => `Trả góp từ ${monthly}/tháng`,
    multiSelectHint: "(chọn nhiều)",
    missingHint: "Vui lòng chọn:",
    decreaseQty: "Giảm số lượng",
    increaseQty: "Tăng số lượng",
    buyNow: "Mua ngay",
    addToCart: "Thêm vào giỏ",
    addToWishlist: "Thêm vào yêu thích",
    removeFromWishlist: "Bỏ yêu thích",
    savedToWishlist: "Đã lưu vào yêu thích",
    chatWithShop: "Chat với shop",
    chatOpening: "Đang mở...",
    freeDelivery: "Giao hàng miễn phí",
    freeDeliveryDesc: "Nhập mã bưu điện để kiểm tra phạm vi giao hàng",
    returnDelivery: "Đổi trả miễn phí",
    returnDeliveryDesc: "Miễn phí đổi trả trong 30 ngày. Xem chi tiết",
    relatedItems: "Sản phẩm liên quan",
    wishButtonLabel: "Yêu thích",
    category: "Danh mục",
    selectOption: (optionName: string, groupName: string) =>
      `Chọn ${optionName} ${groupName}`,
  },

  orders: {
    breadcrumbLabel: "Đơn hàng",
    title: "Đơn hàng của tôi",
    subtitle: "Theo dõi và xem lại tất cả đơn hàng.",
    noOrders: "Chưa có đơn hàng nào.",
    viewDetail: "Xem chi tiết →",
    backToOrders: "← Quay lại đơn hàng",
    orderTitle: (id: number) => `Đơn hàng #${id}`,
    shopLabel: (id: number) => `Shop #${id}`,
    shopCount: (count: number) => `${count} gian hàng`,
    paymentLabel: "thanh toán",
    chatWithShop: "Chat với shop",
    cancelGroupBtn: "Huỷ",
    cancelGroupOk: "Huỷ đơn",
    subtotalLabel: "Tạm tính",
    totalsTitle: "Tổng cộng",
    totalLabel: "Tổng",
    itemsLabel: "Giá hàng",
    shippingLabel: "Phí vận chuyển",
    discountLabel: "Giảm giá",
    finalLabel: "Thành tiền",
    paymentTitle: "Thanh toán",
    paymentMethod: "Phương thức",
    paymentStatus: "Trạng thái",
    shippingAddressTitle: "Địa chỉ giao hàng",
    noAddress: "(chưa có)",
    orderNotFound: "Không tìm thấy đơn hàng",
    refundModalTitle: "Yêu cầu hoàn tiền",
    refundSubmitOk: "Gửi",
    statusFilterAll: "Tất cả",
    statusPending: "Chờ xác nhận",
    statusConfirmed: "Đã xác nhận",
    statusShipping: "Đang giao",
    statusDelivered: "Đã giao",
    statusCancelled: "Đã huỷ",
    cancelConfirm: "Huỷ nhóm đơn hàng này?",
    requestRefund: "Yêu cầu hoàn tiền",
    refundReason: "Lý do",
    refundAmount: "Số tiền hoàn (VND)",
    refundReasonPlaceholder: "Mô tả vấn đề của bạn",
  },

  payment: {
    title: "Kết quả thanh toán",
    successTitle: "Thanh toán thành công",
    failedTitle: "Thanh toán thất bại",
    noInfo: "Không có thông tin thanh toán.",
    viewOrder: (id: number) => `Xem đơn hàng #${id}`,
    myOrders: "Đơn hàng của tôi",
  },

  seller: {
    studioLabel: "Seller Studio",
    activeSeller: "Người bán đang hoạt động",
    sellerSetup: "Thiết lập gian hàng",
    dashboard: {
      title: "Tổng quan gian hàng",
      subtitle: "Theo dõi hiệu suất và quản lý gian hàng của bạn.",
      statTotalProducts: "Tổng sản phẩm",
      statLiveListings: "Đang bán",
      statRevenue: "Doanh thu",
      statTotalOrders: "Tổng đơn hàng",
      statPending: "Chờ xác nhận",
      statDelivered: "Đã giao",
      uploadProductBtn: "+ Đăng sản phẩm",
      viewOrdersBtn: "Xem đơn hàng",
      nextMoveTitle: "Bước tiếp theo",
      nextMoveDesc: "Đăng sản phẩm mới, cập nhật tồn kho và theo dõi xu hướng.",
      createListingBtn: "Tạo sản phẩm mới",
      reviewCatalogBtn: "Xem danh mục",
      fulfillmentTitle: "Danh sách cần làm",
      fulfillmentDesc: "Xác nhận đơn hàng nhanh và cập nhật cho khách mua.",
      openOrdersBtn: "Mở hàng chờ đơn",
    },
    products: {
      title: "Quản lý sản phẩm",
      subtitle: "Cập nhật và duy trì danh sách sản phẩm của bạn.",
      deleteConfirm: "Xoá sản phẩm này? Sản phẩm sẽ bị ẩn khỏi cửa hàng.",
      tableProduct: "Sản phẩm",
      tablePrice: "Giá",
      tableStock: "Tồn kho",
      tableStatus: "Trạng thái",
      statusAll: "Tất cả",
      statusActive: "Đang bán",
      statusDraft: "Nháp",
      emptyText: "Chưa có sản phẩm. Bắt đầu bằng cách đăng sản phẩm mới.",
      uploadProductBtn: "+ Đăng sản phẩm",
      totalMeta: (shown: number, total: number) =>
        `Hiển thị: ${shown} / ${total}`,
    },
    orders: {
      title: "Đơn hàng",
      subtitle: "Quản lý tất cả đơn hàng của gian hàng.",
      statusAll: "Tất cả",
      statusPending: "Chờ xác nhận",
      statusConfirmed: "Đã xác nhận",
      statusShipping: "Đang giao",
      statusDelivered: "Đã giao",
      statusCancelled: "Đã huỷ",
      emptyText: "Chưa có đơn hàng.",
      totalMeta: (shown: number, total: number) =>
        `Hiển thị: ${shown} / ${total}`,
    },
    orderDetail: {
      title: "Chi tiết đơn hàng",
      loadingSubtitle: "Đang tải đơn hàng...",
      notFound: "Không tìm thấy đơn hàng.",
      cancelConfirm: "Huỷ đơn hàng này?",
      qrConfirm: "Xác nhận đã nhận chuyển khoản QR?",
      advancePlaceholder: "Vd: Đã giao cho bưu tá",
      cancelPlaceholder: "Vd: Hết hàng",
      orderItemsTitle: "Các mặt hàng",
      statusHistoryTitle: "Lịch sử trạng thái",
      noLogs: "Chưa có nhật ký.",
      backToOrders: "← Quay lại đơn hàng",
      markAs: (status: string) => `Chuyển sang ${status}`,
      cancelOrderBtn: "Huỷ đơn",
      buyerTitle: "Người mua",
      buyerName: "Tên",
      buyerPhone: "Số điện thoại",
      paymentTitle: "Thanh toán",
      paymentMethod: "Phương thức",
      paymentStatus: "Trạng thái",
      totalsTitle: "Tổng cộng",
      subtotalLabel: "Tạm tính",
      shippingFeeLabel: "Phí vận chuyển",
      totalLabel: "Tổng cộng",
      shippingAddressTitle: "Địa chỉ giao hàng",
      noAddress: "Chưa có địa chỉ.",
      advanceModalTitle: (status: string) => `Chuyển sang ${status}?`,
      advanceModalNote:
        "Thêm ghi chú tuỳ chọn để người mua biết về cập nhật này.",
      advanceModalOk: "Xác nhận",
      cancelModalTitle: "Huỷ đơn hàng này?",
      cancelModalNote: "Cho người mua biết lý do huỷ.",
      cancelModalOk: "Huỷ đơn",
      confirmQRDesc:
        "Đảm bảo đã nhận đúng số tiền với mã giao dịch phù hợp.",
      confirmQROk: "Xác nhận",
      confirmQRBtn: "Tôi đã nhận được tiền",
    },
    apply: {
      title: "Đăng ký bán hàng",
      subtitle: "Gửi thông tin gian hàng. Admin sẽ xem xét và duyệt.",
      loadingTitle: "Đăng ký bán hàng",
      loadingSubtitle: "Đang tải...",
      activeTitle: "Tài khoản người bán đang hoạt động",
      activeSubtitle: "Gian hàng của bạn đã được duyệt.",
      activeStatus: "Tài khoản người bán đang hoạt động",
      activeMessage: "Gian hàng của bạn đã được duyệt.",
      alreadyActive: "Bạn đã là người bán đang hoạt động.",
      goToDashboard: "Vào trang quản lý",
      statusLabel: "Trạng thái:",
      rejectedAlert: "Đơn đăng ký bị từ chối",
      pendingAlert: "Đơn đang được admin xét duyệt.",
      shopNameLabel: "Tên gian hàng",
      descriptionLabel: "Mô tả",
      shopNamePlaceholder: "Moon Store",
      descriptionPlaceholder: "Giao hàng nhanh, hàng chính hãng",
      submitLabel: "Nộp đơn đăng ký",
      resubmitLabel: "Nộp lại đơn đăng ký",
      updateLabel: "Cập nhật đơn đăng ký",
      backToAccount: "Quay lại tài khoản",
    },
    productNew: {
      title: "Đăng sản phẩm mới",
      subtitle: "Đăng bán nhanh chóng với biểu mẫu đơn giản.",
      namePlaceholder: "iPhone 17 Pro Max",
      descPlaceholder: "Mô tả thông số và tình trạng sản phẩm.",
      backToProducts: "← Quay lại sản phẩm",
      nameLabel: "Tên sản phẩm",
      descLabel: "Mô tả ngắn",
      categoryLabel: "Danh mục",
      noCategoriesOption: "Chưa có danh mục",
      brandIdLabel: "ID thương hiệu",
      basePriceLabel: "Giá gốc",
      stockLabel: "Tồn kho",
      imageUrlLabel: "URL hình ảnh",
      statusLabel: "Trạng thái",
      optionGroupsLabel: "Nhóm tuỳ chọn (JSON, tuỳ chọn)",
      tipText: "Mẹo: Dùng ID danh mục/thương hiệu từ cơ sở dữ liệu của bạn.",
      savingBtn: "Đang lưu...",
      publishBtn: "Đăng sản phẩm",
      cancelBtn: "Huỷ",
    },
    productEdit: {
      title: "Chỉnh sửa sản phẩm",
      subtitle: "Cập nhật thông tin, tồn kho và tuỳ chọn sản phẩm.",
      deleteConfirm: "Xoá sản phẩm này? Sản phẩm sẽ bị ẩn khỏi cửa hàng.",
      nameField: "Tên sản phẩm",
      nameRequired: "Tên là bắt buộc",
      namePlaceholder: "iPhone 17 Pro Max",
      descField: "Mô tả",
      statusField: "Trạng thái",
      categoryField: "Danh mục",
      brandField: "Thương hiệu (ID)",
      priceField: "Giá gốc (VND)",
      stockField: "Tồn kho",
      imageField: "URL hình ảnh",
      optionGroupsField: "Nhóm tuỳ chọn (JSON, để trống giữ nguyên)",
      imageUrlPlaceholder: "/images/products/...",
      statusActive: "Đang bán",
      statusDraft: "Nháp",
      backToProducts: "← Quay lại sản phẩm",
      optionGroupsLabel: "Nhóm tuỳ chọn",
      optionGroupsHint:
        "Mỗi nhóm (VD: Màu sắc, Kích cỡ) chứa các tuỳ chọn có thể chọn. Giá thêm được cộng vào giá gốc khi khách chọn.",
      groupNameLabel: "Tên nhóm",
      groupNameRequired: "Tên nhóm là bắt buộc",
      groupNamePlaceholder: "Màu sắc",
      removeGroupBtn: "Xoá nhóm",
      requiredLabel: "Bắt buộc",
      multiSelectLabel: "Chọn nhiều",
      optionNameRequired: "Tên tuỳ chọn là bắt buộc",
      optionNamePlaceholder: "Đỏ",
      priceDeltaPlaceholder: "Giá thêm",
      removeOptionBtn: "Xoá",
      addOptionBtn: "+ Thêm tuỳ chọn",
      addGroupBtn: "+ Thêm nhóm tuỳ chọn",
      deleteBtn: "Xoá sản phẩm",
      saveBtn: "Lưu thay đổi",
    },
    wallet: {
      title: "Ví tiền",
      subtitle: "Theo dõi thu nhập và quản lý rút tiền.",
      requestWithdrawal: "Yêu cầu rút tiền",
      withdrawBtn: "Rút tiền",
      withdrawModalTitle: "Yêu cầu rút tiền",
      withdrawOk: "Gửi",
      amountLabel: "Số tiền (VND)",
      amountRequired: "Vui lòng nhập số tiền",
      amountExceeds: "Số tiền vượt quá số dư khả dụng",
      bankNameLabel: "Tên ngân hàng",
      accountNumberLabel: "Số tài khoản",
      accountHolderLabel: "Chủ tài khoản",
      bankNamePlaceholder: "Vietcombank",
      accountNumberPlaceholder: "Số tài khoản",
      accountHolderPlaceholder: "Họ tên chủ tài khoản",
      availableBalance: "Số dư khả dụng",
      totalEarned: "Tổng thu nhập",
      totalWithdrawn: "Tổng đã rút",
      txHistory: "Lịch sử giao dịch",
      withdrawalRequests: "Yêu cầu rút tiền",
      tableDate: "Ngày",
      tableType: "Loại",
      tableGross: "Doanh thu",
      tableFee: "Phí",
      tableNet: "Thực nhận",
      tableDesc: "Mô tả",
      tableAmount: "Số tiền",
      tableBank: "Ngân hàng",
      tableAccount: "Số tài khoản",
      tableStatus: "Trạng thái",
      tableNote: "Ghi chú",
    },
    chat: {
      title: "Tin nhắn",
      subtitle: "Trò chuyện với khách hàng.",
    },
    nav: {
      dashboard: "Tổng quan",
      orders: "Đơn hàng",
      messages: "Tin nhắn",
      manageProducts: "Quản lý sản phẩm",
      uploadProduct: "Đăng sản phẩm",
      wallet: "Ví tiền",
    },
  },

  admin: {
    consoleLabel: "Admin Console",
    dashboard: {
      title: "Tổng quan hệ thống",
      subtitle: "Thống kê người dùng, người bán và đơn đăng ký.",
      statTotalUsers: "Tổng người dùng",
      statActiveSellers: "Người bán đang hoạt động",
      statPendingApps: "Đơn đăng ký chờ duyệt",
      statAdmins: "Quản trị viên",
      reviewNow: "Xem ngay →",
    },
    sellers: {
      title: "Đơn đăng ký người bán",
      subtitle: "Duyệt và quản lý đơn đăng ký người bán.",
      rejectPlaceholder: "Thông tin gian hàng chưa đầy đủ",
      rejectTitle: "Từ chối đơn đăng ký",
      disableTitle: "Vô hiệu hoá người bán? Sản phẩm của họ sẽ bị ẩn.",
      noApplications: "Không có đơn đăng ký",
      rejectModalText:
        "Cho người bán biết lý do từ chối (tuỳ chọn).",
      rejectReasonPrefix: "Lý do từ chối: ",
      approveBtn: "Duyệt",
      rejectBtn: "Từ chối",
      disableBtn: "Vô hiệu hoá",
      enableBtn: "Kích hoạt",
      rejectOkBtn: "Từ chối",
    },
    users: {
      title: "Người dùng",
      subtitle: "Quản lý vai trò và trạng thái tài khoản.",
      promoteTitle: "Cấp quyền admin cho người dùng này?",
      disableTitle: "Vô hiệu hoá tài khoản này? Họ sẽ không đăng nhập được.",
      noUsers: "Không có người dùng",
      promoteBtn: "Cấp quyền admin",
      promoteOk: "Cấp quyền",
      alreadyAdmin: "Đã là admin",
      disableOk: "Vô hiệu hoá",
      disableBtn: "Vô hiệu hoá",
      enableBtn: "Kích hoạt",
    },
    orders: {
      title: "Đơn hàng",
      subtitle: "Tất cả đơn hàng trên hệ thống.",
      noOrders: "Không có đơn hàng",
      buyerPrefix: "Khách hàng: ",
    },
    categories: {
      title: "Danh mục",
      subtitle: "Quản lý cây danh mục sản phẩm.",
      deleteTitle: "Xoá danh mục này?",
      newCategoryBtn: "Danh mục mới",
      noParent: "(không có danh mục cha)",
      editBtn: "Sửa",
      deleteBtn: "Xoá",
      deleteOk: "Xoá",
      editModalTitle: "Sửa danh mục",
      newModalTitle: "Danh mục mới",
      saveOk: "Lưu",
      nameLabel: "Tên",
      nameRequired: "Tên là bắt buộc",
      namePlaceholder: "Điện thoại",
      parentLabel: "Danh mục cha",
      productCount: (count: number) => `${count} sản phẩm`,
      childCount: (count: number) => `${count} danh mục con`,
    },
    brands: {
      title: "Thương hiệu",
      subtitle: "Quản lý thương hiệu sản phẩm.",
      deleteTitle: "Xoá thương hiệu này?",
      newBrandBtn: "Thương hiệu mới",
      editBtn: "Sửa",
      deleteBtn: "Xoá",
      deleteOk: "Xoá",
      editModalTitle: "Sửa thương hiệu",
      newModalTitle: "Thương hiệu mới",
      saveOk: "Lưu",
      nameLabel: "Tên",
      nameRequired: "Tên là bắt buộc",
      namePlaceholder: "Nova",
      productCount: (count: number) => `${count} sản phẩm`,
    },
    vouchers: {
      title: "Mã giảm giá",
      subtitle: "Tạo và quản lý mã giảm giá toàn hệ thống.",
      codeLabel: "Mã",
      discountTypeLabel: "Loại giảm giá",
      valueLabel: "Giá trị",
      maxDiscountLabel: "Giảm tối đa (tùy chọn)",
      expiredAtLabel: "Ngày hết hạn",
      codePlaceholder: "SUMMER10",
      shopPlaceholder: "Nova",
      newVoucherBtn: "Mã giảm giá mới",
      editBtn: "Sửa",
      deleteBtn: "Xoá",
      deleteOk: "Xoá",
      deleteUsedTitle: "Mã giảm giá đã được dùng; không thể xoá.",
      deleteTitle: "Xoá mã giảm giá?",
      editModalTitle: "Sửa mã giảm giá",
      newModalTitle: "Mã giảm giá mới",
      saveOk: "Lưu",
      codeRequired: "Mã là bắt buộc",
      valueRequired: "Giá trị là bắt buộc",
      expired: "HẾT HẠN",
      active: "ĐANG HOẠT ĐỘNG",
      expires: (date: string) => `Hết hạn ${date}`,
      usedCount: (count: number) => `Đã dùng ${count} lần`,
      maxDiscountMeta: (amount: string) => `giảm tối đa ${amount}`,
    },
    revenue: {
      title: "Doanh thu & Hoa hồng",
      subtitle: "Tổng hợp doanh thu nền tảng và cấu hình hoa hồng.",
      statPlatformRevenue: "Doanh thu nền tảng",
      statTotalTransactions: "Tổng giao dịch",
      statPendingRefunds: "Hoàn tiền chờ xử lý",
      statPendingWithdrawals: "Rút tiền chờ xử lý",
      reviewNow: "Xem ngay →",
      commissionTitle: "Tỉ lệ hoa hồng",
      commissionDesc: (rate: string) =>
        `Tỉ lệ hiện tại: ${rate}%. Người bán nhận (100 − tỉ lệ)% doanh thu sau giao hàng.`,
      updateBtn: "Cập nhật",
    },
    refunds: {
      title: "Yêu cầu hoàn tiền",
      subtitle: "Duyệt và xử lý yêu cầu hoàn tiền của khách hàng.",
      approveBtn: "Duyệt",
      rejectBtn: "Từ chối",
    },
    withdrawals: {
      title: "Yêu cầu rút tiền",
      subtitle: "Duyệt và xử lý yêu cầu rút tiền của người bán.",
      approveBtn: "Duyệt",
      rejectBtn: "Từ chối",
    },
    orderDetail: {
      title: (id: number) => `Đơn hàng #${id}`,
      titleFallback: "Chi tiết đơn hàng",
      loadingSubtitle: "Đang tải...",
      backToOrders: "← Quay lại đơn hàng",
      notFound: "Không tìm thấy đơn hàng",
      buyerTitle: "Người mua",
      buyerName: "Tên",
      buyerEmail: "Email",
      buyerPhone: "Số điện thoại",
      totalsTitle: "Tổng cộng",
      itemsLabel: "Giá hàng",
      shippingLabel: "Phí vận chuyển",
      discountLabel: "Giảm giá",
      finalLabel: "Thành tiền",
      paymentTitle: "Thanh toán",
      paymentMethod: "Phương thức",
      paymentStatus: "Trạng thái",
      shippingTitle: "Địa chỉ giao hàng",
      subtotalLabel: "Tạm tính",
    },
    table: {
      date: "Ngày",
      shop: "Gian hàng",
      amount: "Số tiền",
      bank: "Ngân hàng",
      account: "Số tài khoản",
      holder: "Chủ tài khoản",
      status: "Trạng thái",
      actions: "Hành động",
      order: "Đơn hàng",
      user: "Khách hàng",
      reason: "Lý do",
      reviewLink: "Xem →",
    },
    nav: {
      dashboard: "Tổng quan",
      sellers: "Người bán",
      users: "Người dùng",
      orders: "Đơn hàng",
      categories: "Danh mục",
      brands: "Thương hiệu",
      vouchers: "Mã giảm giá",
      revenue: "Doanh thu",
      refunds: "Hoàn tiền",
      withdrawals: "Rút tiền",
    },
  },

  statusOptions: {
    orderFilter: [
      { label: "Tất cả", value: "ALL" },
      { label: "Chờ xác nhận", value: "PENDING" },
      { label: "Đã xác nhận", value: "CONFIRMED" },
      { label: "Đang giao", value: "SHIPPING" },
      { label: "Đã giao", value: "DELIVERED" },
      { label: "Đã huỷ", value: "CANCELLED" },
    ],
    sellerProductStatus: [
      { label: "Tất cả", value: "ALL" },
      { label: "Đang bán", value: "active" },
      { label: "Nháp", value: "draft" },
    ],
    productStatusOptions: [
      { label: "Đang bán", value: "active" },
      { label: "Nháp", value: "draft" },
    ],
    voucherType: [
      { label: "Phần trăm (%)", value: "percent" },
      { label: "Số tiền cố định", value: "fixed" },
    ],
  },

  notFound: {
    breadcrumbLabel: "404",
    title: "404 Không tìm thấy",
    description:
      "Trang bạn đang tìm không tồn tại. Có thể về trang chủ.",
    backToHome: "Về trang chủ",
  },
};
